sonar.projectKey=ScientiaUFAPE_Scientia
sonar.organization=scientiaufape
sonar.sources=backend/src
sonar.exclusions=backend/src/tests/**
sonar.tests=backend/src/tests
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
